name: pizzeria
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^2.5.3
  cupertino_icons: ^1.0.2
  eva_icons_flutter: ^3.0.2
  firebase_auth: ^3.1.1
  firebase_core: ^1.6.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^4.2.1
  font_awesome_flutter: ^9.1.0
  geocoder:
    git:
      https://github.com/aloisdeniel/flutter_geocoder.git
  geolocator: ^7.6.2
  google_maps_flutter: ^2.0.10
  google_sign_in: ^5.1.1
  provider: ^6.0.1
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: AvantGarde
      fonts:
        - asset: assets/fonts/av.ttf
        - asset: assets/fonts/av2.ttf
